# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_uuid"
version = "1.0.1"
license = "MIT, custom OpenSource license"
author = ["John S. Urban", "Toby White <tow@uszla.me.uk>", "Gen-Tao Chiang <gtc25@cam.ac.uk>", "Andrew Walker <a.walker@ucl.ac.uk>"]
maintainer = "urbanjost@comcast.com"
copyright = "Copyright 2021, John S. Urban, 2005-2009 Toby White, 2007-2009 Gen-Tao Chiang, 2008-2012 Andrew Walker"
description = "module to produce a UUID string"
categories = ["Universally Unique ID"]
keywords = ["fortran", "UUID", "RFC 4122", "Universally Unique ID"]
homepage = "https://github.com/urbanjost/M_uuid.git"

[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true

[install]
   library = true

[[executable]]
   name="unique"
   source-dir="app"
   main="unique.f90"
   [executable.dependencies]
   M_CLI2 = { git = "https://github.com/urbanjost/M_CLI2.git" }

[[test]]
   name="test_suite_M_uuid"
   source-dir="test"
   main="test_suite_M_uuid.f90"
   [test.dependencies]
   M_framework = { git = "https://github.com/urbanjost/M_framework.git" }
