###############################################
#    Install with
# Load the PGI compilers with
module use /opt/nvidia/hpc_sdk/modulefiles
module load nvhpc
###############################################
name: run fpm test on ubuntu with nvfortran

on: [push, pull_request]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest ]
        include:
        - os: ubuntu-latest
          gcc_v: 9

    env:
      FPM_FC: nvfortran
      TZ: UTC+04:00

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install nvfortran Linux
     run: |
      wget https://developer.download.nvidia.com/hpc-sdk/nvhpc_2020_207_Linux_x86_64_cuda_11.0.tar.gz
      tar xpzf nvhpc_2020_207_Linux_x86_64_cuda_11.0.tar.gz
      NVHPC_SILENT=true \
        NVHPC_INSTALL_DIR=/opt/nvidia/hpc_sdk \
        NVHPC_INSTALL_TYPE=single \
        sudo nvhpc_2020_207_Linux_x86_64_cuda_11.0/install
      # Please check https://developer.nvidia.com for documentation,
      # use of NVIDIA HPC SDK software, and other questions.
      yum install environment-modules

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v3
      with:
        use-haskell: ${{ matrix.haskell }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: run fpm test on ubuntu with nvfortran (debug)
      run: fpm test --profile debug

    - name: run fpm test on ubuntu with nvfortran (release)
      run: fpm test --profile release

#    - name: Run demo programs (fpm run)
#      run: fpm run --profile release

    - name: cleanup Linux
      run: ls -ltras
